[tox]
isolated_build = True
envlist = py39, linter, mypy
skipsdist=True

[testenv]
deps =
    pytest
    pytest-cov
    -r{toxinidir}/requirements.txt
commands =
    python -m pytest --cov-report html --cov=src/ 

[testenv:linter]
deps =
    black
    pylint
commands =
    black -l 100 src/ tests/
    pylint --ignore-patterns=test.*?py --fail-under=7.0 --disable import-error src/ tests/

[testenv:mypy]
deps =
    mypy
commands =
    mypy --config-file mypy.ini --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs src