[tox]
isolated_build = True
envlist = py311, linter, mypy
skipsdist=True

[testenv]
allowlist_externals = uv
sitepackages = True
commands =
    uv run pytest --cov-report html --cov=src/ tests/

[testenv:linter]
allowlist_externals = uv
sitepackages = True
commands =
    uv run ruff check src/ tests/
    uv run ruff format src/ tests/

[testenv:mypy]
allowlist_externals = uv
sitepackages = True
commands = 
    uv run mypy --config-file mypy.ini --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs src