loader: ARCADE
image_dir: data/ARCADE/angiogenesis_128/images
label_dir: 
channels:
  - cancer
  - graph
batch_size: 16
val_split: 0.1
test_split: 0.2
keys:
  - ANGIO_Lav
  - ANGIO_Lava
  - ANGIO_Lvav
  - ANGIO_Sav
  - ANGIO_Savav
  - NOANGIO_Lav
  - NOANGIO_Lava
  - NOANGIO_Lvav
  - NOANGIO_Sav
  - NOANGIO_Savav
augmentations:
  # rotate:
  #   degree: 180
labels: