loader: gastruloid
image_dir: data/gastruloid_128/images
image_size: 128
channels:
  - green
batch_size: 30
val_split: 0.2
test_split: 0.2
keys:
  - array1
  # - array2
augmentations:
sequence: False
