loader: gastruloid
image_dir: data/gastruloid/images
label_dir: data/gastruloid/labels
channels:
  - bf
  - stain
batch_size: 32
val_split: 0.1
test_split: 0.2
keys:
  - array1
augmentations:
  # - rotate: 90
  # - rotate: 180