loader: ARCADE
image_dir: data/ARCADE/immortal_vf_128/images
label_dir: data/ARCADE/immortal_vf_128/labels
channels:
  # - cancer
  - graph
batch_size: 16
val_split: 0.1
test_split: 0.2
keys:
  # - CH_Lav
  # - CH_Lava
  # - CH_Lvav
  # - CH_Sav
  # - CH_Savav
  - S_L11
  - S_L12
  - S_L21
  - S_S11
  - S_S22
augmentations:
  # rotate:
  #   degree: 180
labels:
  # - activity
  # - growth
  # - symmetry  