loader: ARCADE
image_dir: data/ARCADE/vascular_function_128/images
label_dir: data/ARCADE/vascular_function_128/labels
channels:
  # - cancer
  - graph
batch_size: 16
val_split: 0.2
test_split: 0.0
keys:
  - CH_Lav
  - CH_Lava
  - CH_Lvav
  - CH_Sav
  - CH_Savav
  - C_Lav
  - C_Lava
  - C_Lvav
  - C_Sav
  - C_Savav
augmentations:
  # rotate:
  #   degree: 180
labels:
  # - activity
  # - growth
  # - symmetry  