num_epochs: 50
continuous:
  image_loss_weight:
    range: 1.0
    search: linear
    num_samples: 1
discrete:
  latent_dim:
    values: [16]
  optimizer:
    values:
      - type: "Adam"
        lr: [0.0001]
        betas: [[0.8, 0.99]]