num_epochs: 50
continuous:
  image_loss_weight:
    range: 0.9
    search: linear
    num_samples: 1
discrete:
  latent_dim:
    values: [2]
  optimizer:
    values:
      - type: "Adam"
        # lr and betas control number of model combinations trained
        lr: [0.001] # removed 0.0001
        betas: [[0.8, 0.99]] # removed [0.9, 0.999]
      # - type: "SGD"
      #   momentum: [0.0, 0.9]
      #   nesterov: [true, false]