num_epochs: 50
continuous:
  image_loss_weight:
    range: 0.9
    search: linear
    num_samples: 1
discrete:
  latent_dim:
    values: [1]
  optimizer:
    values:
      - type: "Adam"
        lr: [0.0001, 0.001]
        betas: [[0.8, 0.99], [0.9, 0.999]]
      # - type: "SGD"
      #   momentum: [0.0, 0.9]
      #   nesterov: [true, false]