num_epochs: 3
continuous:
  image_loss_weight:
    range: 1.0
    search: linear
    num_samples: 1
discrete:
  latent_dim:
    values: [2]
  optimizer:
    values:
      # - type: "Adam"
      #   betas: [[0.9, 0.999], [0.8, 0.99]]
      #   lr: [0.001, 0.01]
      - type: "SGD"
        momentum: [0.0, 0.9]
        nesterov: [true, false]
        lr: [0.001, 0.01]
