num_epochs: 1
continuous:
  image_loss_weight:
    range: 1.0
    search: linear
    num_samples: 1
discrete:
  latent_dim:
    values: [16]
  optimizer:
    values:
      - type: "SGD"
        momentum: [0.9]
        nesterov: [true]
        lr: [0.001]