data_dir: data/ARCADE
models:
  # - 1c_2l
  # - 1c_3l
  - 2c_3l
  # - 2c_3l_1s
  # - 3c_3l
  # - 2c_3l_small
  # - 2c_3l_large
model_configs:
  num_epochs: 3
  batch_size: 32
  val_split: 0.3
  test_split: 0.2
  augmentations:
    - rotate_180
  verbose: true
keys:
  - CH_Lav
  - CH_Lava
  - CH_Lvav
  - CH_Sav
  - CH_Savav
  # - C_Lav
  # - C_Lava
  # - C_Lvav
  # - C_Sav
  # - C_Savav