experiment_name: test
experiments:
  # neuralop:
  #   datasets:
  #     - immortal_vf_128
  #   model:
  #       architecture: neuralop_simple
  #       num_channels: 1
  #       image_size: 128
  #       params: grid_optimizers
  #   general_configs:
  #       pretrain: false
  #       verbose: true  
  # cae:
  #   datasets:
  #     - immortal_vf_128
  #   model:
  #     architecture: cae_simple
  #     num_channels: 1
  #     image_size: 128
  #     params: grid_optimizers
  #   general_configs:
  #     pretrain: false
  #     verbose: true
  ae:
    datasets:
      - immortal_vf_128
    model:
      architecture: ae_simple
      num_channels: 1
      image_size: 128
      params: grid_optimizers
    general_configs:
      pretrain: false
      verbose: true
