data_dir: data/ARCADE
models:
  - 1c_3l
  # - 2c_3l
  # - 2c_3l_1s
  # - 2c_3l_small
  # - 2c_3l_large
  # - 2c_3l_2d
  # - 3c_3l
model_configs:
  num_epochs: 2
  batch_size: 32
  val_split: 0.3
  test_split: 0.2
  augmentations:
    # - rotate_180
  verbose: true
keys:
  - CH_Lav
  # - CH_Lava
  # - CH_Lvav
  # - CH_Sav
  # - CH_Savav
  # - C_Lav
  # - C_Lava
  # - C_Lvav
  # - C_Sav
  # - C_Savav