# build.yml
name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up virtual environment
      run: python -m venv .venv

    - name: Activate virtual environment
      run: source .venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: pytest --cov-report html --cov=src/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        verbose: true
